# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sg_desktop_timelog_dialog.ui'
#
# Created: Mon Dec  2 10:57:32 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ShotgunDesktopTimelogDialog(object):
    def setupUi(self, ShotgunDesktopTimelogDialog):
        ShotgunDesktopTimelogDialog.setObjectName("ShotgunDesktopTimelogDialog")
        ShotgunDesktopTimelogDialog.resize(900, 600)
        self.gridLayout_4 = QtWidgets.QGridLayout(ShotgunDesktopTimelogDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidgetList = QtWidgets.QTabWidget(ShotgunDesktopTimelogDialog)
        self.tabWidgetList.setObjectName("tabWidgetList")
        self.tabMyTask = QtWidgets.QWidget()
        self.tabMyTask.setObjectName("tabMyTask")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabMyTask)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutMyTask = QtWidgets.QGridLayout()
        self.gridLayoutMyTask.setObjectName("gridLayoutMyTask")
        self.lineEditMyTaskSearch = QtWidgets.QLineEdit(self.tabMyTask)
        self.lineEditMyTaskSearch.setObjectName("lineEditMyTaskSearch")
        self.gridLayoutMyTask.addWidget(self.lineEditMyTaskSearch, 0, 0, 1, 1)
        self.treeViewMyTask = QtWidgets.QTreeView(self.tabMyTask)
        self.treeViewMyTask.setObjectName("treeViewMyTask")
        self.gridLayoutMyTask.addWidget(self.treeViewMyTask, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutMyTask, 0, 0, 1, 1)
        self.tabWidgetList.addTab(self.tabMyTask, "")
        self.tabAsset = QtWidgets.QWidget()
        self.tabAsset.setObjectName("tabAsset")
        self.gridLayout = QtWidgets.QGridLayout(self.tabAsset)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutAsset = QtWidgets.QGridLayout()
        self.gridLayoutAsset.setObjectName("gridLayoutAsset")
        self.lineEditAssetSearch = QtWidgets.QLineEdit(self.tabAsset)
        self.lineEditAssetSearch.setObjectName("lineEditAssetSearch")
        self.gridLayoutAsset.addWidget(self.lineEditAssetSearch, 0, 0, 1, 1)
        self.treeViewAsset = QtWidgets.QTreeView(self.tabAsset)
        self.treeViewAsset.setObjectName("treeViewAsset")
        self.gridLayoutAsset.addWidget(self.treeViewAsset, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutAsset, 0, 0, 1, 1)
        self.tabWidgetList.addTab(self.tabAsset, "")
        self.tabShot = QtWidgets.QWidget()
        self.tabShot.setObjectName("tabShot")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabShot)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayoutShot = QtWidgets.QGridLayout()
        self.gridLayoutShot.setObjectName("gridLayoutShot")
        self.treeViewShot = QtWidgets.QTreeView(self.tabShot)
        self.treeViewShot.setObjectName("treeViewShot")
        self.gridLayoutShot.addWidget(self.treeViewShot, 1, 0, 1, 1)
        self.lineEditShotSearch = QtWidgets.QLineEdit(self.tabShot)
        self.lineEditShotSearch.setObjectName("lineEditShotSearch")
        self.gridLayoutShot.addWidget(self.lineEditShotSearch, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayoutShot)
        self.tabWidgetList.addTab(self.tabShot, "")
        self.tabSequence = QtWidgets.QWidget()
        self.tabSequence.setObjectName("tabSequence")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabSequence)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayoutSequence = QtWidgets.QGridLayout()
        self.gridLayoutSequence.setObjectName("gridLayoutSequence")
        self.treeViewSequence = QtWidgets.QTreeView(self.tabSequence)
        self.treeViewSequence.setObjectName("treeViewSequence")
        self.gridLayoutSequence.addWidget(self.treeViewSequence, 1, 0, 1, 1)
        self.lineEditSequenceSearch = QtWidgets.QLineEdit(self.tabSequence)
        self.lineEditSequenceSearch.setObjectName("lineEditSequenceSearch")
        self.gridLayoutSequence.addWidget(self.lineEditSequenceSearch, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayoutSequence, 0, 0, 1, 1)
        self.tabWidgetList.addTab(self.tabSequence, "")
        self.gridLayout_4.addWidget(self.tabWidgetList, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(187)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditDuration = QtWidgets.QLineEdit(ShotgunDesktopTimelogDialog)
        self.lineEditDuration.setObjectName("lineEditDuration")
        self.gridLayout_3.addWidget(self.lineEditDuration, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(ShotgunDesktopTimelogDialog)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.dateEditDate = QtWidgets.QDateEdit(ShotgunDesktopTimelogDialog)
        self.dateEditDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 12, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDate.setCalendarPopup(True)
        self.dateEditDate.setDate(QtCore.QDate(2019, 12, 1))
        self.dateEditDate.setObjectName("dateEditDate")
        self.gridLayout_3.addWidget(self.dateEditDate, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.tableWidgetTimelog = QtWidgets.QTableWidget(ShotgunDesktopTimelogDialog)
        self.tableWidgetTimelog.setObjectName("tableWidgetTimelog")
        self.tableWidgetTimelog.setColumnCount(5)
        self.tableWidgetTimelog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTimelog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTimelog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTimelog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTimelog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTimelog.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.tableWidgetTimelog, 1, 0, 1, 2)
        self.lineEditDescription = QtWidgets.QLineEdit(ShotgunDesktopTimelogDialog)
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.gridLayout_3.addWidget(self.lineEditDescription, 5, 0, 1, 2)
        self.pushButtonSubmit = QtWidgets.QPushButton(ShotgunDesktopTimelogDialog)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.gridLayout_3.addWidget(self.pushButtonSubmit, 6, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 5)

        self.retranslateUi(ShotgunDesktopTimelogDialog)
        self.tabWidgetList.setCurrentIndex(0)
        QtCore.QObject.connect(self.lineEditAssetSearch, QtCore.SIGNAL("returnPressed()"), ShotgunDesktopTimelogDialog.search_asset_slot)
        QtCore.QObject.connect(self.lineEditShotSearch, QtCore.SIGNAL("returnPressed()"), ShotgunDesktopTimelogDialog.search_shot_slot)
        QtCore.QObject.connect(self.lineEditSequenceSearch, QtCore.SIGNAL("returnPressed()"), ShotgunDesktopTimelogDialog.search_sequence_slot)
        QtCore.QObject.connect(self.lineEditMyTaskSearch, QtCore.SIGNAL("returnPressed()"), ShotgunDesktopTimelogDialog.search_mytask_slot)
        QtCore.QObject.connect(self.pushButtonSubmit, QtCore.SIGNAL("clicked()"), ShotgunDesktopTimelogDialog.submit_slot)
        QtCore.QMetaObject.connectSlotsByName(ShotgunDesktopTimelogDialog)

    def retranslateUi(self, ShotgunDesktopTimelogDialog):
        ShotgunDesktopTimelogDialog.setWindowTitle(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "ShotgunVersionDesktop", None, -1))
        self.tabWidgetList.setTabText(self.tabWidgetList.indexOf(self.tabMyTask), QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "MyTasks", None, -1))
        self.tabWidgetList.setTabText(self.tabWidgetList.indexOf(self.tabAsset), QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Assets", None, -1))
        self.tabWidgetList.setTabText(self.tabWidgetList.indexOf(self.tabShot), QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Shots", None, -1))
        self.tabWidgetList.setTabText(self.tabWidgetList.indexOf(self.tabSequence), QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Sequences", None, -1))
        self.lineEditDuration.setPlaceholderText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Duration (Hour)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "TimeLog", None, -1))
        self.dateEditDate.setDisplayFormat(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "yyyy-MM-dd", None, -1))
        self.tableWidgetTimelog.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Person", None, -1))
        self.tableWidgetTimelog.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Date", None, -1))
        self.tableWidgetTimelog.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Duration", None, -1))
        self.tableWidgetTimelog.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Description", None, -1))
        self.tableWidgetTimelog.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Id", None, -1))
        self.lineEditDescription.setPlaceholderText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Description", None, -1))
        self.pushButtonSubmit.setText(QtWidgets.QApplication.translate("ShotgunDesktopTimelogDialog", "Submit", None, -1))

